spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:55432/paylite}
    username: ${DATABASE_USER:paylite}
    password: ${DATABASE_PASSWORD:paylite}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  jackson:
    deserialization:
      accept-float-as-int: false
      fail-on-unknown-properties: true
      fail-on-numbers-for-enums: true
    mapper:
      allow-coercion-of-scalars: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

paylite:
  authorization-ttl: P7D

logging:
  level:
    root: INFO
    io.paylite: DEBUG
